-- Curated dive sites supplied for ReefRadar.
-- This migration is intentionally idempotent against an existing site with the
-- same name and island, or the same name and nearby coordinates. Average
-- visibility remains NULL because the supplied datasets do not include it.

INSERT INTO dive_sites (
    name,
    description,
    country_code,
    country_name,
    region,
    island,
    latitude,
    longitude,
    difficulty,
    average_visibility_meters,
    source_provider,
    source_id
)
SELECT
    seed.name,
    seed.description,
    seed.country_code,
    seed.country_name,
    seed.region,
    seed.island,
    seed.latitude,
    seed.longitude,
    seed.difficulty,
    seed.average_visibility_meters::INTEGER,
    seed.source_provider,
    seed.source_id
FROM (VALUES
    ('Barracuda Point', 'Wall dive site where divers report barracuda tornado, reef sharks, turtles.', 'MY', 'Malaysia', 'Sabah', 'Sipadan Island', 4.114000, 118.628000, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-sabah-sipadan-island-barracuda-point'),
    ('South Point', 'Wall dive site where divers report hammerhead sharks, eagle rays.', 'MY', 'Malaysia', 'Sabah', 'Sipadan Island', 4.109000, 118.626000, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-sabah-sipadan-island-south-point'),
    ('Drop Off', 'Wall dive site where divers report wall dive, turtles, bumphead parrotfish.', 'MY', 'Malaysia', 'Sabah', 'Sipadan Island', 4.112000, 118.630000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-sabah-sipadan-island-drop-off'),
    ('Turtle Cavern', 'Cave dive site where divers report cavern, turtle skeletons.', 'MY', 'Malaysia', 'Sabah', 'Sipadan Island', 4.112500, 118.629500, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-sabah-sipadan-island-turtle-cavern'),
    ('Hanging Gardens', 'Wall dive site where divers report soft corals, turtles.', 'MY', 'Malaysia', 'Sabah', 'Sipadan Island', 4.111000, 118.624000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-sabah-sipadan-island-hanging-gardens'),
    ('White-Tip Avenue', 'Wall dive site where divers report white-tip reef sharks.', 'MY', 'Malaysia', 'Sabah', 'Sipadan Island', 4.115000, 118.623000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-sabah-sipadan-island-white-tip-avenue'),
    ('Coral Gardens', 'Reef dive site where divers report coral reef, turtles.', 'MY', 'Malaysia', 'Sabah', 'Sipadan Island', 4.116000, 118.627000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-sabah-sipadan-island-coral-gardens'),
    ('West Ridge', 'Wall dive site where divers report sharks, drift diving.', 'MY', 'Malaysia', 'Sabah', 'Sipadan Island', 4.107000, 118.621000, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-sabah-sipadan-island-west-ridge'),
    ('Lobster Lair', 'Wall dive site where divers report lobsters, reef sharks.', 'MY', 'Malaysia', 'Sabah', 'Sipadan Island', 4.108000, 118.620000, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-sabah-sipadan-island-lobster-lair'),
    ('Turtle Patch', 'Reef dive site where divers report green turtles.', 'MY', 'Malaysia', 'Sabah', 'Sipadan Island', 4.117000, 118.631000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-sabah-sipadan-island-turtle-patch'),
    ('Mid Reef', 'Reef dive site where divers report grey reef sharks.', 'MY', 'Malaysia', 'Sabah', 'Sipadan Island', 4.118000, 118.629000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-sabah-sipadan-island-mid-reef'),
    ('North Point', 'Wall dive site where divers report pelagics, reef sharks.', 'MY', 'Malaysia', 'Sabah', 'Sipadan Island', 4.119000, 118.625000, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-sabah-sipadan-island-north-point'),
    ('Froggy Lair', 'Muck dive site where divers report frogfish, nudibranchs.', 'MY', 'Malaysia', 'Sabah', 'Mabul Island', 4.246000, 118.628000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-sabah-mabul-island-froggy-lair'),
    ('Paradise 1', 'Muck dive site where divers report macro photography.', 'MY', 'Malaysia', 'Sabah', 'Mabul Island', 4.247000, 118.629000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-sabah-mabul-island-paradise-1'),
    ('Paradise 2', 'Muck dive site where divers report ghost pipefish.', 'MY', 'Malaysia', 'Sabah', 'Mabul Island', 4.248000, 118.630000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-sabah-mabul-island-paradise-2'),
    ('Seaventure Platform', 'Artificial Reef dive site where divers report macro life, artificial reef.', 'MY', 'Malaysia', 'Sabah', 'Mabul Island', 4.243000, 118.624000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-sabah-mabul-island-seaventure-platform'),
    ('Eel Garden', 'Sand dive site where divers report garden eels.', 'MY', 'Malaysia', 'Sabah', 'Mabul Island', 4.245000, 118.627000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-sabah-mabul-island-eel-garden'),
    ('Mandarin Valley', 'Reef dive site where divers report mandarin fish.', 'MY', 'Malaysia', 'Sabah', 'Mabul Island', 4.244000, 118.626000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-sabah-mabul-island-mandarin-valley'),
    ('House Reef', 'Reef dive site where divers report mandarin fish, macro.', 'MY', 'Malaysia', 'Sabah', 'Kapalai', 4.232000, 118.652000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-sabah-kapalai-house-reef'),
    ('Magic Rock', 'Reef dive site where divers report macro life.', 'MY', 'Malaysia', 'Sabah', 'Kapalai', 4.230000, 118.651000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-sabah-kapalai-magic-rock'),
    ('Cape Kri', 'Reef dive site where divers report highest fish biodiversity.', 'ID', 'Indonesia', 'Southwest Papua', 'Raja Ampat', -0.563000, 130.671000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-id-southwest-papua-raja-ampat-cape-kri'),
    ('Blue Magic', 'Seamount dive site where divers report oceanic manta rays.', 'ID', 'Indonesia', 'Southwest Papua', 'Raja Ampat', -0.557000, 130.674000, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-id-southwest-papua-raja-ampat-blue-magic'),
    ('Manta Sandy', 'Reef dive site where divers report manta cleaning station.', 'ID', 'Indonesia', 'Southwest Papua', 'Raja Ampat', -0.589000, 130.640000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-id-southwest-papua-raja-ampat-manta-sandy'),
    ('Sardine Reef', 'Reef dive site where divers report large fish schools.', 'ID', 'Indonesia', 'Southwest Papua', 'Raja Ampat', -0.562000, 130.668000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-id-southwest-papua-raja-ampat-sardine-reef'),
    ('Melissa''s Garden', 'Reef dive site where divers report hard coral garden.', 'ID', 'Indonesia', 'Southwest Papua', 'Raja Ampat', 0.001000, 130.130000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-id-southwest-papua-raja-ampat-melissa-s-garden'),
    ('Blue Corner', 'Reef dive site where divers report pelagic fish.', 'ID', 'Indonesia', 'Southwest Papua', 'Raja Ampat', -0.560000, 130.660000, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-id-southwest-papua-raja-ampat-blue-corner'),
    ('Chicken Reef', 'Reef dive site where divers report coral diversity.', 'ID', 'Indonesia', 'Southwest Papua', 'Raja Ampat', -0.580000, 130.620000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-id-southwest-papua-raja-ampat-chicken-reef'),
    ('Boo Windows', 'Reef dive site where divers report rock formations, soft corals.', 'ID', 'Indonesia', 'Southwest Papua', 'Misool', -2.186000, 130.513000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-id-southwest-papua-misool-boo-windows'),
    ('Magic Mountain', 'Seamount dive site where divers report oceanic mantas.', 'ID', 'Indonesia', 'Southwest Papua', 'Misool', -2.221000, 130.556000, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-id-southwest-papua-misool-magic-mountain'),
    ('Fiabacet', 'Reef dive site where divers report soft corals.', 'ID', 'Indonesia', 'Southwest Papua', 'Misool', -2.114000, 130.429000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-id-southwest-papua-misool-fiabacet'),
    ('Four Kings', 'Reef dive site where divers report pelagic fish.', 'ID', 'Indonesia', 'Southwest Papua', 'Misool', -2.120000, 130.430000, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-id-southwest-papua-misool-four-kings'),
    ('Crystal Rock', 'Pinnacle dive site where divers report grey reef sharks.', 'ID', 'Indonesia', 'East Nusa Tenggara', 'Komodo', -8.548000, 119.606000, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-id-east-nusa-tenggara-komodo-crystal-rock'),
    ('Castle Rock', 'Pinnacle dive site where divers report trevallies, sharks.', 'ID', 'Indonesia', 'East Nusa Tenggara', 'Komodo', -8.551000, 119.609000, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-id-east-nusa-tenggara-komodo-castle-rock'),
    ('Manta Alley', 'Reef dive site where divers report reef mantas.', 'ID', 'Indonesia', 'East Nusa Tenggara', 'Komodo', -8.700000, 119.580000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-id-east-nusa-tenggara-komodo-manta-alley'),
    ('Manta Point', 'Reef dive site where divers report manta rays.', 'ID', 'Indonesia', 'East Nusa Tenggara', 'Komodo', -8.660000, 119.570000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-id-east-nusa-tenggara-komodo-manta-point'),
    ('Batu Bolong', 'Pinnacle dive site where divers report spectacular coral.', 'ID', 'Indonesia', 'East Nusa Tenggara', 'Komodo', -8.539000, 119.631000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-id-east-nusa-tenggara-komodo-batu-bolong'),
    ('Golden Passage', 'Drift dive site where divers report drift dive.', 'ID', 'Indonesia', 'East Nusa Tenggara', 'Komodo', -8.542000, 119.615000, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-id-east-nusa-tenggara-komodo-golden-passage'),
    ('Cauldron', 'Drift dive site where divers report strong currents.', 'ID', 'Indonesia', 'East Nusa Tenggara', 'Komodo', -8.500000, 119.670000, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-id-east-nusa-tenggara-komodo-cauldron'),
    ('Shotgun', 'Drift dive site where divers report fast drift.', 'ID', 'Indonesia', 'East Nusa Tenggara', 'Komodo', -8.501000, 119.671000, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-id-east-nusa-tenggara-komodo-shotgun'),
    ('Yellow Wall', 'Wall dive site where divers report soft corals.', 'ID', 'Indonesia', 'East Nusa Tenggara', 'Komodo', -8.541000, 119.628000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-id-east-nusa-tenggara-komodo-yellow-wall'),
    ('Richelieu Rock', 'Pinnacle dive site where divers report whale sharks, macro life.', 'TH', 'Thailand', 'Phang Nga', 'Surin Islands', 9.372600, 98.038200, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-th-phang-nga-surin-islands-richelieu-rock'),
    ('Koh Bon Ridge', 'Ridge dive site where divers report manta rays.', 'TH', 'Thailand', 'Phang Nga', 'Similan Islands', 8.680000, 97.640000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-th-phang-nga-similan-islands-koh-bon-ridge'),
    ('Koh Tachai Pinnacle', 'Pinnacle dive site where divers report whale sharks.', 'TH', 'Thailand', 'Phang Nga', 'Similan Islands', 8.850000, 97.820000, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-th-phang-nga-similan-islands-koh-tachai-pinnacle'),
    ('Elephant Head Rock', 'Boulder dive site where divers report swim-throughs.', 'TH', 'Thailand', 'Phang Nga', 'Similan Islands', 8.649000, 97.644000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-th-phang-nga-similan-islands-elephant-head-rock'),
    ('Christmas Point', 'Reef dive site where divers report granite boulders.', 'TH', 'Thailand', 'Phang Nga', 'Similan Islands', 8.663000, 97.640000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-th-phang-nga-similan-islands-christmas-point'),
    ('West of Eden', 'Reef dive site where divers report soft corals.', 'TH', 'Thailand', 'Phang Nga', 'Similan Islands', 8.651000, 97.645000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-th-phang-nga-similan-islands-west-of-eden'),
    ('East of Eden', 'Reef dive site where divers report coral garden.', 'TH', 'Thailand', 'Phang Nga', 'Similan Islands', 8.654000, 97.648000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-th-phang-nga-similan-islands-east-of-eden'),
    ('Anita''s Reef', 'Reef dive site where divers report macro life.', 'TH', 'Thailand', 'Phang Nga', 'Similan Islands', 8.646000, 97.642000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-th-phang-nga-similan-islands-anita-s-reef'),
    ('Shark Fin Reef', 'Reef dive site where divers report leopard sharks.', 'TH', 'Thailand', 'Phang Nga', 'Similan Islands', 8.640000, 97.646000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-th-phang-nga-similan-islands-shark-fin-reef'),
    ('Chumphon Pinnacle', 'Pinnacle dive site where divers report barracuda, whale sharks.', 'TH', 'Thailand', 'Surat Thani', 'Koh Tao', 10.132400, 99.828700, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-th-surat-thani-koh-tao-chumphon-pinnacle'),
    ('Southwest Pinnacle', 'Pinnacle dive site where divers report whale sharks.', 'TH', 'Thailand', 'Surat Thani', 'Koh Tao', 10.040000, 99.770000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-th-surat-thani-koh-tao-southwest-pinnacle'),
    ('Sail Rock', 'Pinnacle dive site where divers report whale sharks.', 'TH', 'Thailand', 'Surat Thani', 'Koh Phangan', 10.083300, 99.916700, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-th-surat-thani-koh-phangan-sail-rock'),
    ('Twins', 'Reef dive site where divers report coral reef.', 'TH', 'Thailand', 'Surat Thani', 'Koh Tao', 10.090000, 99.820000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-th-surat-thani-koh-tao-twins'),
    ('White Rock', 'Reef dive site where divers report turtles.', 'TH', 'Thailand', 'Surat Thani', 'Koh Tao', 10.095000, 99.825000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-th-surat-thani-koh-tao-white-rock'),
    ('Tiger Reef', 'Reef dive site where divers report blacktip reef sharks, schooling fish.', 'MY', 'Malaysia', 'Pahang', 'Tioman Island', 2.790800, 104.131500, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-pahang-tioman-island-tiger-reef'),
    ('Chebeh Island', 'Reef dive site where divers report healthy corals, turtles.', 'MY', 'Malaysia', 'Pahang', 'Tioman Island', 2.842400, 104.106800, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-pahang-tioman-island-chebeh-island'),
    ('Labas', 'Reef dive site where divers report gorgonian sea fans, reef fish.', 'MY', 'Malaysia', 'Pahang', 'Tioman Island', 2.831500, 104.137200, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-pahang-tioman-island-labas'),
    ('Soyak Island', 'Reef dive site where divers report soft corals, turtles.', 'MY', 'Malaysia', 'Pahang', 'Tioman Island', 2.814800, 104.166500, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-pahang-tioman-island-soyak-island'),
    ('Renggis Island', 'Reef dive site where divers report coral garden, turtles.', 'MY', 'Malaysia', 'Pahang', 'Tioman Island', 2.804200, 104.145600, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-pahang-tioman-island-renggis-island'),
    ('Fan Canyon', 'Wall dive site where divers report sea fans, nudibranchs.', 'MY', 'Malaysia', 'Pahang', 'Tioman Island', 2.828600, 104.132800, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-pahang-tioman-island-fan-canyon'),
    ('Marine Park', 'Reef dive site where divers report coral garden.', 'MY', 'Malaysia', 'Pahang', 'Tioman Island', 2.818500, 104.159000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-pahang-tioman-island-marine-park'),
    ('Coral Island', 'Reef dive site where divers report hard corals.', 'MY', 'Malaysia', 'Pahang', 'Tioman Island', 2.821400, 104.170800, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-pahang-tioman-island-coral-island'),
    ('Seven Skies', 'Reef dive site where divers report reef sharks, pelagics.', 'MY', 'Malaysia', 'Pahang', 'Tioman Island', 2.771000, 104.171200, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-pahang-tioman-island-seven-skies'),
    ('Tokong Bahara', 'Pinnacle dive site where divers report strong currents, pelagics.', 'MY', 'Malaysia', 'Pahang', 'Tioman Island', 2.736800, 104.167400, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-pahang-tioman-island-tokong-bahara'),
    ('Tokong Burung', 'Pinnacle dive site where divers report large fish schools.', 'MY', 'Malaysia', 'Pahang', 'Tioman Island', 2.726400, 104.205800, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-pahang-tioman-island-tokong-burung'),
    ('Pulau Tulai House Reef', 'Reef dive site where divers report macro life.', 'MY', 'Malaysia', 'Pahang', 'Tioman Island', 2.844700, 104.113500, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-pahang-tioman-island-pulau-tulai-house-reef'),
    ('Fan Garden', 'Reef dive site where divers report sea fans.', 'MY', 'Malaysia', 'Pahang', 'Tioman Island', 2.825500, 104.138800, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-pahang-tioman-island-fan-garden'),
    ('Mini Mount', 'Pinnacle dive site where divers report reef fish.', 'MY', 'Malaysia', 'Pahang', 'Tioman Island', 2.783100, 104.151700, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-pahang-tioman-island-mini-mount'),
    ('Batu Malang', 'Reef dive site where divers report rock formations.', 'MY', 'Malaysia', 'Pahang', 'Tioman Island', 2.802000, 104.127900, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-pahang-tioman-island-batu-malang'),
    ('Tokong Laut', 'Pinnacle dive site where divers report large schools of jacks.', 'MY', 'Malaysia', 'Terengganu', 'Redang Island', 5.790400, 103.012500, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-redang-island-tokong-laut'),
    ('Tanjung Tokong', 'Reef dive site where divers report coral reef.', 'MY', 'Malaysia', 'Terengganu', 'Redang Island', 5.787100, 103.009800, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-redang-island-tanjung-tokong'),
    ('Big Mount', 'Pinnacle dive site where divers report barracuda, trevallies.', 'MY', 'Malaysia', 'Terengganu', 'Redang Island', 5.782400, 103.004300, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-redang-island-big-mount'),
    ('Mini Mount', 'Pinnacle dive site where divers report coral bommies.', 'MY', 'Malaysia', 'Terengganu', 'Redang Island', 5.784600, 103.002100, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-redang-island-mini-mount'),
    ('Pulau Ling', 'Reef dive site where divers report hard coral.', 'MY', 'Malaysia', 'Terengganu', 'Redang Island', 5.799200, 103.018000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-redang-island-pulau-ling'),
    ('Che Isa', 'Reef dive site where divers report coral garden.', 'MY', 'Malaysia', 'Terengganu', 'Redang Island', 5.801400, 103.021400, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-redang-island-che-isa'),
    ('House Reef', 'Reef dive site where divers report macro life.', 'MY', 'Malaysia', 'Terengganu', 'Redang Island', 5.785000, 103.005000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-redang-island-house-reef'),
    ('Tunnel Point', 'Wall dive site where divers report swim-throughs.', 'MY', 'Malaysia', 'Terengganu', 'Redang Island', 5.789300, 103.010200, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-redang-island-tunnel-point'),
    ('Terumbu Kili', 'Reef dive site where divers report turtles.', 'MY', 'Malaysia', 'Terengganu', 'Redang Island', 5.792000, 103.014500, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-redang-island-terumbu-kili'),
    ('Sha''ab Helang', 'Reef dive site where divers report eagle rays.', 'MY', 'Malaysia', 'Terengganu', 'Redang Island', 5.786300, 103.016000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-redang-island-sha-ab-helang'),
    ('Sugar Wreck', 'Wreck dive site where divers report artificial wreck.', 'MY', 'Malaysia', 'Terengganu', 'Perhentian Islands', 5.921800, 102.729500, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-perhentian-islands-sugar-wreck'),
    ('Police Wreck', 'Wreck dive site where divers report patrol boat wreck.', 'MY', 'Malaysia', 'Terengganu', 'Perhentian Islands', 5.919500, 102.726700, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-perhentian-islands-police-wreck'),
    ('Temple of the Sea', 'Reef dive site where divers report coral pinnacles.', 'MY', 'Malaysia', 'Terengganu', 'Perhentian Islands', 5.930600, 102.734100, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-perhentian-islands-temple-of-the-sea'),
    ('T3', 'Reef dive site where divers report large coral heads.', 'MY', 'Malaysia', 'Terengganu', 'Perhentian Islands', 5.925800, 102.731600, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-perhentian-islands-t3'),
    ('D''Lagoon Reef', 'Reef dive site where divers report turtles.', 'MY', 'Malaysia', 'Terengganu', 'Perhentian Islands', 5.934200, 102.733200, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-perhentian-islands-d-lagoon-reef'),
    ('Shark Point', 'Reef dive site where divers report blacktip reef sharks.', 'MY', 'Malaysia', 'Terengganu', 'Perhentian Islands', 5.927500, 102.729000, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-perhentian-islands-shark-point'),
    ('Tokong Laut', 'Pinnacle dive site where divers report pelagic fish.', 'MY', 'Malaysia', 'Terengganu', 'Perhentian Islands', 5.947000, 102.742300, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-perhentian-islands-tokong-laut'),
    ('Secret Reef', 'Reef dive site where divers report macro life.', 'MY', 'Malaysia', 'Terengganu', 'Perhentian Islands', 5.924600, 102.730500, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-perhentian-islands-secret-reef'),
    ('Romantic Beach Reef', 'Reef dive site where divers report coral garden.', 'MY', 'Malaysia', 'Terengganu', 'Perhentian Islands', 5.919900, 102.723800, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-perhentian-islands-romantic-beach-reef'),
    ('Vietnam Wreck', 'Wreck dive site where divers report historic wreck.', 'MY', 'Malaysia', 'Terengganu', 'Perhentian Islands', 5.938100, 102.742500, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-perhentian-islands-vietnam-wreck'),
    ('Tanjung Api', 'Wall dive site where divers report whitetip reef sharks.', 'MY', 'Malaysia', 'Terengganu', 'Tenggol Island', 4.807600, 103.677400, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-tenggol-island-tanjung-api'),
    ('Tokong Timur', 'Pinnacle dive site where divers report pelagics.', 'MY', 'Malaysia', 'Terengganu', 'Tenggol Island', 4.816100, 103.688300, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-tenggol-island-tokong-timur'),
    ('Tokong West', 'Pinnacle dive site where divers report barracuda.', 'MY', 'Malaysia', 'Terengganu', 'Tenggol Island', 4.801700, 103.667200, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-tenggol-island-tokong-west'),
    ('Coral Garden', 'Reef dive site where divers report hard coral.', 'MY', 'Malaysia', 'Terengganu', 'Tenggol Island', 4.806000, 103.681200, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-tenggol-island-coral-garden'),
    ('Water Point', 'Reef dive site where divers report schooling fish.', 'MY', 'Malaysia', 'Terengganu', 'Tenggol Island', 4.809800, 103.676000, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-tenggol-island-water-point'),
    ('Pasir Tenggol', 'Sand dive site where divers report macro life.', 'MY', 'Malaysia', 'Terengganu', 'Tenggol Island', 4.812300, 103.680100, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-tenggol-island-pasir-tenggol'),
    ('Rajawali Reef', 'Reef dive site where divers report turtles.', 'MY', 'Malaysia', 'Terengganu', 'Tenggol Island', 4.808900, 103.684400, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-tenggol-island-rajawali-reef'),
    ('Tokong Burung', 'Pinnacle dive site where divers report grey reef sharks.', 'MY', 'Malaysia', 'Terengganu', 'Tenggol Island', 4.821400, 103.693700, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-terengganu-tenggol-island-tokong-burung'),
    ('Dogtooth Lair', 'Wall dive site where divers report hammerhead sharks.', 'MY', 'Malaysia', 'Sabah', 'Layang-Layang', 7.371500, 113.843800, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-sabah-layang-layang-dogtooth-lair'),
    ('D Wall', 'Wall dive site where divers report hammerheads.', 'MY', 'Malaysia', 'Sabah', 'Layang-Layang', 7.368900, 113.845100, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-sabah-layang-layang-d-wall'),
    ('Valley of the Rays', 'Wall dive site where divers report eagle rays.', 'MY', 'Malaysia', 'Sabah', 'Layang-Layang', 7.369800, 113.846400, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-sabah-layang-layang-valley-of-the-rays'),
    ('Gorgonian Forest', 'Wall dive site where divers report large sea fans.', 'MY', 'Malaysia', 'Sabah', 'Layang-Layang', 7.372400, 113.842700, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-sabah-layang-layang-gorgonian-forest'),
    ('Blue Hole', 'Wall dive site where divers report vertical wall.', 'MY', 'Malaysia', 'Sabah', 'Layang-Layang', 7.370700, 113.844900, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-sabah-layang-layang-blue-hole'),
    ('Shark Cave', 'Wall dive site where divers report grey reef sharks.', 'MY', 'Malaysia', 'Sabah', 'Layang-Layang', 7.367800, 113.843300, 'ADVANCED', NULL, 'USER_SUPPLIED', 'curated-my-sabah-layang-layang-shark-cave'),
    ('Coral Garden', 'Reef dive site where divers report hard corals.', 'MY', 'Malaysia', 'Sabah', 'Layang-Layang', 7.373000, 113.846800, 'BEGINNER', NULL, 'USER_SUPPLIED', 'curated-my-sabah-layang-layang-coral-garden'),
    ('Wrasse Strip', 'Wall dive site where divers report napoleon wrasse.', 'MY', 'Malaysia', 'Sabah', 'Layang-Layang', 7.371900, 113.845800, 'INTERMEDIATE', NULL, 'USER_SUPPLIED', 'curated-my-sabah-layang-layang-wrasse-strip')
) AS seed (
    name,
    description,
    country_code,
    country_name,
    region,
    island,
    latitude,
    longitude,
    difficulty,
    average_visibility_meters,
    source_provider,
    source_id
)
WHERE NOT EXISTS (
    SELECT 1
    FROM dive_sites existing
    WHERE LOWER(existing.name) = LOWER(seed.name)
      AND existing.country_code = seed.country_code
      AND (
          LOWER(COALESCE(existing.island, '')) = LOWER(COALESCE(seed.island, ''))
          OR (
              ABS(existing.latitude - seed.latitude) < 0.020000
              AND ABS(existing.longitude - seed.longitude) < 0.020000
          )
      )
)
ON CONFLICT (source_provider, source_id)
    WHERE source_provider IS NOT NULL
      AND source_id IS NOT NULL
    DO NOTHING;
