-- Curated species commonly reported by divers in Southeast Asian waters.
-- Scientific names should be periodically reviewed against WoRMS:
-- https://www.marinespecies.org/
--
-- Existing records and their IDs are preserved. Scientific-name conflicts are
-- skipped so existing sightings continue to reference the same species rows.

INSERT INTO species (
    common_name,
    scientific_name,
    category,
    description
)
VALUES
    ('Whale Shark', 'Rhincodon typus', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Whitetip Reef Shark', 'Triaenodon obesus', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Blacktip Reef Shark', 'Carcharhinus melanopterus', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Grey Reef Shark', 'Carcharhinus amblyrhynchos', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Silvertip Shark', 'Carcharhinus albimarginatus', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Tiger Shark', 'Galeocerdo cuvier', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bull Shark', 'Carcharhinus leucas', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Oceanic Whitetip Shark', 'Carcharhinus longimanus', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Scalloped Hammerhead', 'Sphyrna lewini', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Great Hammerhead', 'Sphyrna mokarran', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Pelagic Thresher Shark', 'Alopias pelagicus', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bigeye Thresher Shark', 'Alopias superciliosus', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Common Thresher Shark', 'Alopias vulpinus', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Tawny Nurse Shark', 'Nebrius ferrugineus', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Zebra Shark', 'Stegostoma tigrinum', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Indonesian Wobbegong', 'Orectolobus leptolineatus', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Tasselled Wobbegong', 'Eucrossorhinus dasypogon', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Spotted Wobbegong', 'Orectolobus maculatus', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Brownbanded Bamboo Shark', 'Chiloscyllium punctatum', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Whitespotted Bamboo Shark', 'Chiloscyllium plagiosum', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Grey Bamboo Shark', 'Chiloscyllium griseum', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Epaulette Shark', 'Hemiscyllium ocellatum', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Walking Shark', 'Hemiscyllium halmahera', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Zebra Bullhead Shark', 'Heterodontus zebra', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Megamouth Shark', 'Megachasma pelagios', 'SHARK', 'A shark included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Giant Manta Ray', 'Mobula birostris', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Reef Manta Ray', 'Mobula alfredi', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Spotted Eagle Ray', 'Aetobatus ocellatus', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bluespotted Ribbontail Ray', 'Taeniura lymma', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bluespotted Maskray', 'Neotrygon kuhlii', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Pink Whipray', 'Pateobatis fai', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Jenkins Whipray', 'Pateobatis jenkinsii', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Marbled Ray', 'Taeniurops meyeni', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Cowtail Stingray', 'Pastinachus ater', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Porcupine Ray', 'Urogymnus asperrimus', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Mangrove Whipray', 'Urogymnus granulatus', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Reticulate Whipray', 'Himantura uarnak', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Blackspotted Whipray', 'Himantura astra', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bowmouth Guitarfish', 'Rhina ancylostoma', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Giant Guitarfish', 'Glaucostegus typus', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bottlenose Wedgefish', 'Rhynchobatus australiae', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Ornate Eagle Ray', 'Aetomylaeus vespertilio', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Banded Eagle Ray', 'Aetomylaeus nichofii', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Shortfin Devil Ray', 'Mobula kuhlii', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Spinetail Devil Ray', 'Mobula mobular', 'RAY', 'A ray included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Green Sea Turtle', 'Chelonia mydas', 'TURTLE', 'A sea turtle included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Hawksbill Sea Turtle', 'Eretmochelys imbricata', 'TURTLE', 'A sea turtle included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Loggerhead Sea Turtle', 'Caretta caretta', 'TURTLE', 'A sea turtle included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Olive Ridley Sea Turtle', 'Lepidochelys olivacea', 'TURTLE', 'A sea turtle included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Leatherback Sea Turtle', 'Dermochelys coriacea', 'TURTLE', 'A sea turtle included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Great Barracuda', 'Sphyraena barracuda', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Yellowtail Barracuda', 'Sphyraena flavicauda', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Pickhandle Barracuda', 'Sphyraena jello', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Dogtooth Tuna', 'Gymnosarda unicolor', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Yellowfin Tuna', 'Thunnus albacares', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Wahoo', 'Acanthocybium solandri', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Rainbow Runner', 'Elagatis bipinnulata', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Indo-Pacific Sailfish', 'Istiophorus platypterus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Mahi-mahi', 'Coryphaena hippurus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Ocean Sunfish', 'Mola mola', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Cobia', 'Rachycentron canadum', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Milkfish', 'Chanos chanos', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Great Seahorse', 'Hippocampus kelloggi', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Giant Grouper', 'Epinephelus lanceolatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Brown-marbled Grouper', 'Epinephelus fuscoguttatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Camouflage Grouper', 'Epinephelus polyphekadion', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Honeycomb Grouper', 'Epinephelus merra', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Blacktip Grouper', 'Epinephelus fasciatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('White-streaked Grouper', 'Epinephelus ongus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Coral Grouper', 'Epinephelus corallicola', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Malabar Grouper', 'Epinephelus malabaricus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Orange-spotted Grouper', 'Epinephelus coioides', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Humpback Grouper', 'Cromileptes altivelis', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Leopard Coral Grouper', 'Plectropomus leopardus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Squaretail Coral Grouper', 'Plectropomus areolatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Saddleback Grouper', 'Plectropomus laevis', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Highfin Coral Grouper', 'Plectropomus oligacanthus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Spotted Coral Grouper', 'Plectropomus maculatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Twinspot Snapper', 'Lutjanus bohar', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Checkered Snapper', 'Lutjanus decussatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bluestripe Snapper', 'Lutjanus kasmira', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Humpback Red Snapper', 'Lutjanus gibbus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('One-spot Snapper', 'Lutjanus monostigma', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Dory Snapper', 'Lutjanus fulviflamma', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Mangrove Red Snapper', 'Lutjanus argentimaculatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Emperor Red Snapper', 'Lutjanus sebae', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Two-spot Banded Snapper', 'Lutjanus biguttatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Five-lined Snapper', 'Lutjanus quinquelineatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Giant Trevally', 'Caranx ignobilis', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bluefin Trevally', 'Caranx melampygus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bigeye Trevally', 'Caranx sexfasciatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Tille Trevally', 'Caranx tille', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Brassy Trevally', 'Caranx papuensis', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Golden Trevally', 'Gnathanodon speciosus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Doublespotted Queenfish', 'Scomberoides lysan', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Snubnose Pompano', 'Trachinotus blochii', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Almaco Jack', 'Seriola rivoliana', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Threadfin Butterflyfish', 'Chaetodon auriga', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Raccoon Butterflyfish', 'Chaetodon lunula', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Sunburst Butterflyfish', 'Chaetodon kleinii', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Blackback Butterflyfish', 'Chaetodon melannotus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Scrawled Butterflyfish', 'Chaetodon meyeri', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Ornate Butterflyfish', 'Chaetodon ornatissimus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Latticed Butterflyfish', 'Chaetodon rafflesii', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Ovalspot Butterflyfish', 'Chaetodon speculum', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Chevron Butterflyfish', 'Chaetodon trifascialis', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Teardrop Butterflyfish', 'Chaetodon unimaculatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Vagabond Butterflyfish', 'Chaetodon vagabundus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Triangular Butterflyfish', 'Chaetodon baronessa', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Saddled Butterflyfish', 'Chaetodon ephippium', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Longfin Bannerfish', 'Heniochus acuminatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Emperor Angelfish', 'Pomacanthus imperator', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Semicircle Angelfish', 'Pomacanthus semicirculatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Sixbar Angelfish', 'Pomacanthus sexstriatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Blueface Angelfish', 'Pomacanthus xanthometopon', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bluering Angelfish', 'Pomacanthus annularis', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Majestic Angelfish', 'Pomacanthus navarchus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Regal Angelfish', 'Pygoplites diacanthus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bicolor Angelfish', 'Centropyge bicolor', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Flame Angelfish', 'Centropyge loricula', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Lemonpeel Angelfish', 'Centropyge flavissima', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bluestreak Cleaner Wrasse', 'Labroides dimidiatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Humphead Wrasse', 'Cheilinus undulatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Redbreasted Wrasse', 'Cheilinus fasciatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Floral Wrasse', 'Cheilinus chlorourus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Tripletail Wrasse', 'Cheilinus trilobatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Moon Wrasse', 'Thalassoma lunare', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Sixbar Wrasse', 'Thalassoma hardwicke', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Jansen''s Wrasse', 'Thalassoma jansenii', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Blunthead Wrasse', 'Thalassoma amblycephalum', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Yellowtail Coris', 'Coris gaimard', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Clown Coris', 'Coris aygula', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Spotted Wrasse', 'Anampses meleagrides', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Blue-spotted Wrasse', 'Anampses caeruleopunctatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Checkerboard Wrasse', 'Halichoeres hortulanus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Tailspot Wrasse', 'Halichoeres melanurus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Steephead Parrotfish', 'Chlorurus microrhinos', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Daisy Parrotfish', 'Chlorurus sordidus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bleeker''s Parrotfish', 'Chlorurus bleekeri', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Stronghead Parrotfish', 'Chlorurus strongylocephalus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Blue-barred Parrotfish', 'Scarus ghobban', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Ember Parrotfish', 'Scarus rubroviolaceus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Dusky Parrotfish', 'Scarus niger', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bridled Parrotfish', 'Scarus frenatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Quoy''s Parrotfish', 'Scarus quoyi', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Singapore Parrotfish', 'Scarus prasiognathos', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Titan Triggerfish', 'Balistoides viridescens', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Clown Triggerfish', 'Balistoides conspicillum', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Picasso Triggerfish', 'Rhinecanthus aculeatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Rectangle Triggerfish', 'Rhinecanthus rectangulus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Redtoothed Triggerfish', 'Odonus niger', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Pinktail Triggerfish', 'Melichthys vidua', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Yellowmargin Triggerfish', 'Pseudobalistes flavimarginatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Scrawled Filefish', 'Aluterus scriptus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Harlequin Filefish', 'Oxymonacanthus longirostris', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bristletail Filefish', 'Acreichthys tomentosus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('White-spotted Puffer', 'Arothron hispidus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Guineafowl Puffer', 'Arothron meleagris', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Blackspotted Puffer', 'Arothron nigropunctatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Starry Puffer', 'Arothron stellatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Saddled Puffer', 'Canthigaster valentini', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Pygmy Seahorse', 'Hippocampus bargibanti', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Denise''s Pygmy Seahorse', 'Hippocampus denise', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Spotted Seahorse', 'Hippocampus kuda', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Tiger-tail Seahorse', 'Hippocampus comes', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Thorny Seahorse', 'Hippocampus histrix', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Ornate Ghost Pipefish', 'Solenostomus paradoxus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Robust Ghost Pipefish', 'Solenostomus cyanopterus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Mandarinfish', 'Synchiropus splendidus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Spotted Mandarinfish', 'Synchiropus picturatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Clown Frogfish', 'Antennarius maculatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Giant Frogfish', 'Antennarius commerson', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Painted Frogfish', 'Antennarius pictus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Striated Frogfish', 'Antennarius striatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Shaggy Frogfish', 'Antennarius hispidus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Weedy Scorpionfish', 'Rhinopias frondosa', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Paddle-flap Scorpionfish', 'Rhinopias eschmeyeri', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Red Lionfish', 'Pterois volitans', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Spotfin Lionfish', 'Pterois antennata', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Leaf Scorpionfish', 'Taenianotus triacanthus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Giant Moray', 'Gymnothorax javanicus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Yellow-edged Moray', 'Gymnothorax flavimarginatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Whitemouth Moray', 'Gymnothorax meleagris', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Undulated Moray', 'Gymnothorax undulatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Fimbriated Moray', 'Gymnothorax fimbriatus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Greyface Moray', 'Gymnothorax thyrsoideus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Peppered Moray', 'Gymnothorax pictus', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Snowflake Moray', 'Echidna nebulosa', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Barred Moray', 'Echidna polyzona', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Ribbon Eel', 'Rhinomuraena quaesita', 'FISH', 'A fish included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Blue-ringed Octopus', 'Hapalochlaena lunulata', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Wonderpus', 'Wunderpus photogenicus', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Mimic Octopus', 'Thaumoctopus mimicus', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Coconut Octopus', 'Amphioctopus marginatus', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Day Octopus', 'Octopus cyanea', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Broadclub Cuttlefish', 'Sepia latimanus', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Flamboyant Cuttlefish', 'Metasepia pfefferi', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Stumpy-spined Cuttlefish', 'Sepia bandensis', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bigfin Reef Squid', 'Sepioteuthis lessoniana', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Giant Clam', 'Tridacna gigas', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Small Giant Clam', 'Tridacna maxima', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Fluted Giant Clam', 'Tridacna squamosa', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Boring Giant Clam', 'Tridacna crocea', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Southern Giant Clam', 'Tridacna derasa', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Willan''s Chromodoris', 'Chromodoris willani', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Anna''s Chromodoris', 'Chromodoris annae', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Loch''s Chromodoris', 'Chromodoris lochi', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Magnificent Chromodoris', 'Chromodoris magnifica', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bullock''s Hypselodoris', 'Hypselodoris bullockii', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Purple Hypselodoris', 'Hypselodoris apolegma', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Variable Neon Slug', 'Nembrotha kubaryana', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Crested Nembrotha', 'Nembrotha cristata', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Pikachu Nudibranch', 'Thecacera pacifica', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Scrambled Egg Nudibranch', 'Phyllidia varicosa', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Ocellated Phyllidia', 'Phyllidia ocellata', 'MOLLUSK', 'A mollusk included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Peacock Mantis Shrimp', 'Odontodactylus scyllarus', 'CRUSTACEAN', 'A crustacean included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Harlequin Shrimp', 'Hymenocera picta', 'CRUSTACEAN', 'A crustacean included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Anemone Shrimp', 'Ancylomenes magnificus', 'CRUSTACEAN', 'A crustacean included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Banded Coral Shrimp', 'Stenopus hispidus', 'CRUSTACEAN', 'A crustacean included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Pacific Cleaner Shrimp', 'Lysmata amboinensis', 'CRUSTACEAN', 'A crustacean included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Hinge-beak Shrimp', 'Rhynchocinetes durbanensis', 'CRUSTACEAN', 'A crustacean included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Sexy Shrimp', 'Thor amboinensis', 'CRUSTACEAN', 'A crustacean included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Spotted Porcelain Crab', 'Neopetrolisthes maculatus', 'CRUSTACEAN', 'A crustacean included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('White-spotted Hermit Crab', 'Dardanus megistos', 'CRUSTACEAN', 'A crustacean included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Painted Spiny Lobster', 'Panulirus versicolor', 'CRUSTACEAN', 'A crustacean included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Ornate Spiny Lobster', 'Panulirus ornatus', 'CRUSTACEAN', 'A crustacean included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Boxer Crab', 'Lybia tessellata', 'CRUSTACEAN', 'A crustacean included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Decorator Crab', 'Camposcia retusa', 'CRUSTACEAN', 'A crustacean included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Green Mantis Shrimp', 'Gonodactylaceus falcatus', 'CRUSTACEAN', 'A crustacean included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Emperor Shrimp', 'Zenopontonia rex', 'CRUSTACEAN', 'A crustacean included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Table Coral', 'Acropora hyacinthus', 'CORAL', 'A coral included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Staghorn Coral', 'Acropora muricata', 'CORAL', 'A coral included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Digitated Coral', 'Acropora humilis', 'CORAL', 'A coral included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Pocillopora Coral', 'Pocillopora damicornis', 'CORAL', 'A coral included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Cauliflower Coral', 'Pocillopora verrucosa', 'CORAL', 'A coral included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Smooth Cauliflower Coral', 'Stylophora pistillata', 'CORAL', 'A coral included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Birdsnest Coral', 'Seriatopora hystrix', 'CORAL', 'A coral included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Lobe Coral', 'Porites lobata', 'CORAL', 'A coral included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Finger Coral', 'Porites cylindrica', 'CORAL', 'A coral included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Mushroom Coral', 'Fungia fungites', 'CORAL', 'A coral included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Slipper Coral', 'Herpolitha limax', 'CORAL', 'A coral included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Knob Coral', 'Dipsastraea speciosa', 'CORAL', 'A coral included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Galaxy Coral', 'Galaxea fascicularis', 'CORAL', 'A coral included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Black Sun Coral', 'Tubastraea micranthus', 'CORAL', 'A coral included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Bubble Coral', 'Physogyra lichtensteini', 'CORAL', 'A coral included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Crown-of-thorns Starfish', 'Acanthaster planci', 'OTHER', 'A marine animal included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Blue Sea Star', 'Linckia laevigata', 'OTHER', 'A marine animal included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Prickly Redfish', 'Thelenota ananas', 'OTHER', 'A marine animal included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Medusa Worm', 'Synapta maculata', 'OTHER', 'A marine animal included in ReefRadar''s curated Southeast Asian diving directory.'),
    ('Paper Sponge', 'Phyllospongia papyracea', 'OTHER', 'A marine animal included in ReefRadar''s curated Southeast Asian diving directory.')
ON CONFLICT (scientific_name) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_species_common_name_lower
    ON species (LOWER(common_name));

CREATE INDEX IF NOT EXISTS idx_species_scientific_name_lower
    ON species (LOWER(scientific_name));

