CREATE TABLE dive_sites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    latitude DECIMAL(9, 6) NOT NULL,
    longitude DECIMAL(9, 6) NOT NULL,
    difficulty VARCHAR(30) NOT NULL,
    average_visibility_meters INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO dive_sites (
    name,
    description,
    latitude,
    longitude,
    difficulty,
    average_visibility_meters
)
VALUES
(
    'Sipadan Island',
    'Malaysian dive site known for turtles, barracuda and reef sharks.',
    4.1147,
    118.6280,
    'ADVANCED',
    25
),
(
    'Mabul Island',
    'Popular macro-diving site with nudibranchs and frogfish.',
    4.2450,
    118.6310,
    'BEGINNER',
    15
);
