CREATE TABLE species (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    common_name VARCHAR(150) NOT NULL,
    scientific_name VARCHAR(200) NOT NULL UNIQUE,
    category VARCHAR(50) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO species (
    common_name,
    scientific_name,
    category,
    description
)
VALUES
(
    'Green Sea Turtle',
    'Chelonia mydas',
    'TURTLE',
    'A large sea turtle commonly observed around tropical reefs.'
),
(
    'Great Barracuda',
    'Sphyraena barracuda',
    'FISH',
    'A large predatory fish found around reefs and open water.'
),
(
    'Giant Manta Ray',
    'Mobula birostris',
    'RAY',
    'A large ray often observed near cleaning stations.'
);
