CREATE TABLE dive_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dive_site_id BIGINT NOT NULL,
    dive_date DATE NOT NULL,
    max_depth_meters DECIMAL(5, 2) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    water_temperature_celsius DECIMAL(4, 1),
    visibility_meters INTEGER,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_dive_logs_dive_site
        FOREIGN KEY (dive_site_id)
        REFERENCES dive_sites(id),

    CONSTRAINT chk_positive_depth
        CHECK (max_depth_meters > 0),

    CONSTRAINT chk_positive_duration
        CHECK (duration_minutes > 0)
);
