CREATE TABLE sightings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dive_log_id BIGINT NOT NULL,
    species_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sightings_dive_log
        FOREIGN KEY (dive_log_id)
        REFERENCES dive_logs(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_sightings_species
        FOREIGN KEY (species_id)
        REFERENCES species(id),

    CONSTRAINT chk_sighting_quantity
        CHECK (quantity > 0),

    CONSTRAINT uq_sighting_dive_species
        UNIQUE (dive_log_id, species_id)
);

CREATE INDEX idx_sightings_dive_log
    ON sightings(dive_log_id);

CREATE INDEX idx_sightings_species
    ON sightings(species_id);