spring.application.name=ReefRadar

server.port=${PORT:8080}

SPRING_DATASOURCE_URL=jdbc:postgresql://INTERNAL_HOST:5432/reefradarspring.datasource.username=${SPRING_DATASOURCE_USERNAME:reefradar}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:uJtfhinMFhOvi85kqIXwQkTKd8GuVEUA}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=${SHOW_SQL:false}

spring.flyway.enabled=true

app.jwt.secret=${JWT_SECRET:local-development-secret-key-32-chars}
app.jwt.expiration=${JWT_EXPIRATION:PT2H}

spring.devtools.restart.additional-exclude=db/migration/**